title: csd3
lang: en
description: A collection of CSD3 notes
encoding: UTF-8
baseurl: /csd3
url: https://cambridge-ceu.github.io

theme: null

debug:
  compress: false
  dist: false
  shortcodes: true

lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false

mathjax:
  tex:
    inlineMath:
      - ["$", "$"]
      - ['\\(', '\\)']
  svg:
    fontCache: "global"

readme_index:
  enabled: true # Ensures the plugin is active
  with_frontmatter: true # Only treat README.md as index if it contains YAML front matter (like your `sort: 2`)
  show_sorted: false # Do NOT automatically list directory contents below README content
  remove_originals: false # Keep the original README.md file accessible as /Python/README.html (optional)
  auto_title: false # Prevents auto-generating a title from the first heading in README.md
  auto_description: false # Prevents auto-generating meta description from README.md content

plugins:
  - jekyll-default-layout
  - jekyll-readme-index
  - jekyll-github-metadata
  - jekyll-titles-from-headings
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - .github
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
