#!/usr/bin/bash

#SBATCH --job-name=_gwas_catalog
#SBATCH --mem=28800
#SBATCH --time=12:00:00

#SBATCH --account CARDIO-SL0-CPU
#SBATCH --partition cardio
#SBATCH --qos=cardio

#SBATCH --export ALL
#SBATCH --array=1-91
#SBATCH --output=_%A_%a.o
#SBATCH --error=_%A_%a.e

export src=~/rds/results/private/proteomics/scallop-inf1
export dst=~/rds/results/public/proteomics/scallop-inf1

if [ ! -f "${dst}/files.lst" ]; then
   ls ${src}/*gz | xargs -l -I {} basename {} -1.tbl.gz | sed 's/-/\t/'| cut -f1 > ${dst}/files.lst
fi

export protein=$(awk 'NR==ENVIRON["SLURM_ARRAY_TASK_ID"]' "${dst}/files.lst")

(
  echo chromosome base_pair_location effect_allele other_allele beta standard_error effect_allele_frequency p_value variant_id n
  zcat ${src}/${protein}-1.tbl.gz | \
  awk -v chr=${chr} '
    NR>1 && $1==chr
    {
      gsub(/chr/,"",$3)
      print $1,$2,$4,$5,$10,$11,-$12,$6,$3,$18
    }' | \
  sort -k1,1n -k2,2n
) | \
tr ' ' '\t' | \
bgzip -f > "${dst}/${protein}.gz"
tabix -S1 -s1 -b2 -e2 -f "${dst}/${protein}.gz"
