title: csd3
lang: en
description: A collection of CSD3 notes

remote_theme: rundocs/jekyll-rtd-theme

debug:
  compress: true
  dist: false
  shortcodes: false

readme_index:
  with_frontmatter: true

mermaid:
  initialize:
    startOnLoad: true
    logLevel: fatal
    flowchart:
      diagramPadding: 8
      htmlLabels: true
      curve: linear
    gantt:
      titleTopMargin: 25

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
