title: csd3
description: A collection of CSD3 notes

theme: null

debug:
  compress: true
  dist: false
  shortcodes: false

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-spaceship

exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - csd3.gemspec
  - st.sh

jekyll-spaceship:
  # default enabled processors
  processors:
    - table-processor
    - mathjax-processor
    - plantuml-processor
    - mermaid-processor
    - polyfill-processor
    - media-processor
    - emoji-processor
    - element-processor
  mathjax-processor:
    src:
      - https://polyfill.io/v3/polyfill.min.js?features=es6
      - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    config:
      tex:
        inlineMath:
          - ["$", "$"]
          - ['\(', '\)']
        displayMath:
          - ["$$", "$$"]
          - ['\[', '\]']
      svg:
        fontCache: "global"
    optimize: # optimization on building stage to check and add mathjax scripts
      enabled: true # value `false` for adding to all pages
      include: [] # include patterns for math expressions checking (regexp)
      exclude: [] # exclude patterns for math expressions checking (regexp)
  plantuml-processor:
    mode: default # mode value 'pre-fetch' for fetching image at building stage
    css:
      class: plantuml
    syntax:
      code: "plantuml!"
      custom: ["@startuml", "@enduml"]
    src: http://www.plantuml.com/plantuml/svg/
  mermaid-processor:
    mode: default # mode value 'pre-fetch' for fetching image at building stage
    css:
      class: mermaid
    syntax:
      code: "mermaid!"
      custom: ["@startmermaid", "@endmermaid"]
    config:
      theme: default
    src: https://mermaid.ink/svg/
  media-processor:
    default:
      id: "media-{id}"
      class: "media"
      width: "100%"
      height: 350
      frameborder: 0
      style: "max-width: 600px; outline: none;"
      allow: "encrypted-media; picture-in-picture"
  emoji-processor:
    css:
      class: emoji
    src: https://github.githubassets.com/images/icons/emoji/
